---
execute: 
  echo: false
page-layout: full
editor_options: 
  chunk_output_type: console
---

```{r}
#| message: false

library(tidyverse)
library(gt)
library(glue)

workshops <- read_csv("workshops.csv") |>
  mutate(
    day_1 = glue("[{day_1}](/workshops/{day_1_slug}/)"),
    day_2 = glue("[{day_2}](/workshops/{day_2_slug}/)"),
    day_2 = if_else(type == "2-day", "", day_2),
    day_2_instructor = if_else(type == "2-day", "", day_2_instructor),
    type = paste0("**", type, " workshops**")
  ) |>
  select(-room, -contains("slug")) 
```

Choose one of the 2-day workshops or a 1-day workshop for each day.
Go to <https://posit.co/conference> to register!

```{r}
#| results: asis

workshops |>
  gt(groupname_col = "type", process_md = TRUE) |>
  fmt_url(columns = c(day_1, day_2)) |>
  cols_width(
    no ~ pct(8),
    day_1 ~ pct(46),
    day_2 ~ pct(46) 
  ) |>
  cols_align(
    align = "left",
    columns = c(day_1, day_2)
  ) |>
  tab_style(
    style = cell_borders(
      sides = c("right"),
      style = "solid"
    ),
    locations = cells_body(
      columns = day_1,
      rows = c(5:18)
    )
  ) |>
  tab_style(
    style = cell_borders(
      sides = c("right"),
      style = "solid"
    ),
    locations = cells_body(
      columns = c(no, day_2),
      rows = everything()
    )
  ) |>
  cols_merge(
    columns = c(day_1, day_1_instructor),
    pattern = "{1}<br>&nbsp;&nbsp;{2}"
  ) |>
  cols_merge(
    columns = c(day_2, day_2_instructor),
    pattern = "{1}<br>&nbsp;&nbsp;{2}"
  ) |>
  tab_style(
    style = list(
      cell_fill(color = "lightgray")
    ),
    locations = cells_row_groups()
  ) |>
  cols_label(
    day_1 = "Day 1 - Sep 17",
    day_2 = "Day 2 - Sep 18",
    no = ""
  ) |>
  tab_options(quarto.disable_processing = TRUE)
```
