---
title: "Deploy and maintain models with vetiver"
author: "Julia Silge"
date: "2023-09-18"
length: "B-1-day"
day-one: " "
day-two: "X"
languages:
  - R
  - Python
tags:
  - modelling
  - deployment
---

# Abstract

Many data scientists understand what goes into training a machine learning or statistical model, but creating a strategy to deploy and maintain that model can be daunting.
In this workshop, learn what MLOps (machine learning operations) is, what principles can be used to create a practical MLOps strategy, and what kinds of tasks and components are involved.
We'll use vetiver, a framework for MLOps tasks in Python and R, to version, deploy, and monitor the models you have trained and want to deploy and maintain in production reliably and efficiently.

# Target audience

We expect participants to have exposure to basic modeling and machine learning practice, but NOT expert familiarity with advanced ML or MLOps topics.

This workshop is for you if you:

-   have intermediate R **or** Python knowledge (this will be a "choose your own adventure" workshop where you can work through the exercises in either R or Python)

-   can read data from CSV and other flat files, transform and reshape data, and make a wide variety of graphs

-   can fit a model to data with your modeling framework of choice

# Bio

**Julia Silge** is a data scientist and software engineer at Posit PBC (formerly RStudio) where she works on open source modeling and MLOps tools.
She is an author, an international keynote speaker, and a real-world practitioner focusing on data analysis and machine learning.
Julia loves text analysis, making beautiful charts, and communicating about technical topics with diverse audiences.
