---
title: "Steal like an Rtist: Creative Coding in R"
author: "Ijeamaka Anyene Fumagalli + Sharla Gelfand"
date: "2023-09-17"
length: "B-1-day"
day-one: "X"
day-two: " "
languages:
  - R
tags:
  - visualization
  - programming
  - art
---

# Abstract

R is a tool for data analysis, but also can be used for self expression.
This workshop will be an introduction to creative coding in R in order to make visual art.
We will take an inspiration-first approach, using compelling pieces to discuss and learn the techniques that shape the work.
This workshop takes guidance from its namesake, the book "Steal Like An Artist" by Austin Kleon - once we have identified and learned to recreate existing works, we will cover how to take this inspiration and transform, remix, or reinterpret it in the pursuit of developing our own work and artistic styles. 
\
\
This workshop is hands on and will cover colour theory and manipulation, a reintroduction of the data frame as the foundation for creating art (instead of just for analyzing data!), using ggplot2 as an artistic canvas, creating basic and specialized shapes, tiling and pattern making, developing your own functions and using iteration.
We will also discuss how to use controlled randomness to convert a standalone piece into a generative art system that can produce many distinct outputs.
Creative coding may seem a world apart from data analysis, but we see a large overlap and intersection of the skills used in both, not to mention the creative muscles that are already used in data visualization.

# Target audience

This course will be appropriate if:

-   you are comfortable with R and RStudio, experience with tidyverse and ggplot2

-   you are interested in applying data visualization skills more creatively, but may not know where to start or how to develop style/inspiration

-   you are an artists interested in exploring code as another medium for creating their work

# Bio

**Ijeamaka Anyene Fumagalli** is a full-time senior data analyst in the healthcare space and a free time computational artist.
Using code, mainly the R programming language, she creates data art and generative art systems.
She loves all things grid based, minimal, and geometric which naturally led to her love for textile arts as well.

**Sharla Gelfand** is a freelance statistician, software developer, and artist with interests in web development, generative art, and textile arts.
Their work explores the play between art created by a computer and by hand, creating generative art that looks like it could have been made by hand (like a textile, drawing, or painting), and making physical art based on data or outputs of a generative system, exploring the strengths and limitations of each.
