---
title: "Advanced tidymodels"
author: "Max Kuhn"
date: "2023-09-17"
length: "B-1-day"
description: "1-day workshop"
day-one: "X"
day-two: " "
languages:
  - R
tags:
  - tidymodels
  - modelling
---

# Description

You will learn about model optimization using the tune package and deepen your understanding of what's possible in preprocessing with recipes.
Additionally, we'll highlight time series analysis using tidymodels.
Time permitting, model ensembles via stacking will be introduced.
This course is focused on the analysis of tabular data and does not include deep learning methods.
Participants who have completed the "Introduction to tidymodels" workshop will be well-prepared for this course.

# Audience

::: callout-warning
Need one more bullet point.
:::

This workshop is for you if you:

-   have used tidymodels packages like recipes, rsample, and parsnip and are comfortable with tidyverse syntax (e.g. piping, mutates, pivoting),
-   have some experience with resampling and modeling (e.g., linear regression, random forests, etc.), but we don't expect you to be an expert in these, and
-   ...

Participants who are new to tidymodels will benefit from taking the [Introduction to tidymodels](/tidymodels-intro/) workshop before joining this one.

# Instructor

**Max Kuhn** is a software engineer at Posit.
He is responsible for the tidymodels ecosystem and maintains about 30 packages, including caret.
He was applying models in the pharmaceutical and diagnostic industries for over 18 years.
Max has a Ph.D. in Biostatistics.
He, and Kjell Johnson, wrote the book Applied Predictive Modeling, which won the Ziegel award from the American Statistical Association.
Their second book, Feature Engineering and Selection, was published in 2019 and the book Tidy Models with R was published in 2022.
