---
title: "Shiny in production: Tools and Techniques"
author: "Eric Nantz"
date: "2023-09-18"
length: "B-1-day"
description: "1-day workshop"
day-one: " "
day-two: "X"
languages:
  - R
tags:
  - shiny
  - deployment
---

# Description

Shiny brings tremendous possibilities to share innovative data science workflows with others inside an intuitive web interface.
Many in the Shiny community have shared effective development techniques for building a robust application.
Even with the best intentions during application development, a myriad of issues can arise once it leaves the confines of your machine. 
In this one-day workshop, you will implement core techniques to account for common scenarios that arise once your application is used in production, such as accounting for thousands of simultaneous users, how effective profiling can address performance bottlenecks, and ensuring your application is doing as little as possible to ensure a smooth and responsive experience.
 

# Audience

This course assumes intermediate knowledge of building Shiny applications in R and prior experience deploying an application to a platform such as the [shinyapps.io](https://www.google.com/url?q=http://shinyapps.io&source=gmail-imap&ust=1675909279000000&usg=AOvVaw16Rb7h20MkEcMyfHS3Xlot) service or products like Posit Connect.

This course is for you if you:

-   had a Shiny application work just fine on your machine, but encounters critical issues after deployment,
-   are eager to prospectively apply techniques before deployment to plan for the unexpected, and
-   want to know the benefits and trade-offs between various ways of hosting Shiny applications.

# Instructor

**Eric Nantz** is a director within the statistical innovation center at Eli Lilly and Company, creating analytical pipelines and capabilities of advanced statistical methodologies for clinical design used in multiple phases of development.
Outside of his day job, Eric is passionate about connecting with and showcasing the brilliant R community in multiple ways.
You may recognize his voice from the [R-Podcast](https://r-podcast.org) that he launched in 2012.
Eric is also the creator of the [Shiny Developer Series](https://shinydevseries.com) where he interviews authors of Shiny-related packages and practitioners developing applications, as well as sharing his own R and Shiny adventures via live streams on his [Twitch channel](https://twitch.tv/rpodcast).
In addition, Eric is a curator for the [RWeekly project](https://rweekly.org) and co-host of the [RWeekly Highlights podcast](https://rweekly.fireside.fm) which accompanies every issue.
