---
title: "Introduction to the tidyverse"
author: "Posit Academy Team"
date: "2023-09-17"
length: "A-2-day"
description: "2-day workshop"
day-one: "X"
day-two: "X"
languages:
  - R
tags:
  - data science
  - tidyverse
---

# Description

This is not a standard workshop, but a six-week online apprenticeship that culminates in two in-person days at posit::conf(2023). Here, you will learn the foundations of R and the Tidyverse under the guidance of a Posit Academy mentor and in the company of a close group of fellow learners. You will be expected to complete a weekly curriculum of interactive tutorials, and to attend a weekly presentation meeting with your mentor and fellow students. Topics will include the basics of R, importing data, visualizing data with ggplot2, wrangling data with dplyr and tidyr, working with strings, factors, and date-times, modelling data with base R, and reporting reproducibly with quarto. Begins August 7th, 2023. No knowledge of R required. Visit [posit.co/academy](https://www.google.com/url?q=http://posit.co/academy&source=gmail-imap&ust=1676588939000000&usg=AOvVaw21BohFX4j-xCOFPKh2MeLz) to learn more about this uniquely effective learning format.

# Audience

This course is ideal for:

-   those new to R or the Tidyverse,

-   anyone who has dabbled in R, but now wants a rigorous foundation in up-to-date data science best practices, or

-   SAS and Excel users looking to switch their workflows to R.

# Instructor

Posit Academy is Posit's internal team of data scientists and educators. We provide a cohort-based, mentor-led, hands-on data science apprenticeship for working professionals. It is delivered on an online platform with interactive coding exercises and frequent cross-student collaboration.
