---
title: "DevOps for Data Scientists"
author: "Rika Gorn"
date: "2023-09-17"
length: "A-2-day"
description: "2-day workshop"
day-one: "X"
day-two: "X"
languages:
  - R
  - Shell scripting
tags:
  - admin
---

# Description

In this workshop, we will discuss ways to better deploy, scale, and containerize your Data products!  We'll use both R and shell scripting to virtualize Posit products in the cloud. You'll learn enough  Linux sysadmin, security, and authorization to be dangerous - or at least to understand your IT and DevSecOps teams. By the end of the workshop you will have the tools to start deploying your own data science assets into production. 


# Audience

This workshop is for you if you:

-   Are a Data Scientist or Analyst who wants to put their work into production

-   want to learn a little more about Docker containers and virtual machines

-   want to better understand how DevOps, IT, or security can be leveraged to support the work of Data Scientists

-   are responsible for the administration of Posit Workbench, Posit Connect, or Posit Package Manager at your organization

# Instructor

**Rika Gorn** is a Solutions Engineer at Posit, where she helps organizations deploy, configure, and use Posit Products as well as open source tooling. Before coming to Posit, Rika worked as a Data Science Manager at a mental health tech company. 
