---
title: "Enhancing Communication & Collaboration in Data Science with Quarto and Jupyter Notebooks"
author: "Hamel Husain"
date: "2023-09-18"
length: "B-1-day"
description: "1-day workshop"
day-one: " "
day-two: "X"
languages:
  - Python
tags:
  - quarto
  - notebooks
  - python
---

# Description

Sharing knowledge through writing is a critical aspect of scientific activity, including data science. It allows researchers to communicate their findings and insights to a wider audience, build upon existing work, and collaborate with others in their field. However, until recently, there have been limited options for publishing long-form writing and expository analyses authored in Jupyter Notebooks, a popular medium for data scientists.

Enter Quarto - an innovative, open-source scientific and technical publishing system compatible with Jupyter Notebooks and other popular mediums. Quarto provides data scientists with a seamless way to publish their work in a high-quality format that is easily accessible and shareable. With Quarto, researchers can turn their Jupyter Notebooks into professional-looking publications in a variety of formats, including web pages, books, and slides.

In this talk, we will demonstrate how Quarto enables data scientists to turn their work products into professional, high-quality publications, websites, blog posts, and other shareable artifacts.  As a bonus, we will also discuss how you can create and document Python packages using Jupyter notebooks and Quarto with the help of [nbdev](https://nbdev.fast.ai/).

The learning outcomes for the workshop include:

-   examine case studies where sharing scientific knowledge has greatly improved the efficacy of data science teams.

-   author documents in plain text markdown or Jupyter notebooks with equations, citations, crossrefs, figure panels, callouts, and advanced layouts.

-   learn how to author content in IPython/Jupyter and the Quarto VS Code extension.

-   leverage Quarto for creating different types of publications, including personal blogs, knowledge management for teams, notes, books, websites, and presentation slides.

-   extend Quarto with notebook filters and extensions.

-   host websites and publications on platforms like GitHub Pages, QuartoPub, and Netlify.

-   test notebooks and documentation with Quarto's execution options.

-   create and document Python packages with [nbdev](https://nbdev.fast.ai/) and Quarto. 

# Audience

This workshop is for you if you:

-   have some experience with Python and Jupyter and want to learn how Quarto can support and enhance your workflows,
-   want to learn about turning your notebooks to websites and publications and
-   want to learn how to write python packages with Jupyter notebooks and Quarto with the help of [nbdev](https://nbdev.fast.ai/).

The workshop will assume some prior experience with Python and Jupyter Notebooks.

# Instructors

This workshop will be taught by [Hamel Husain](https://hamel.dev).
